<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer' . '/autoload_real.php';

/**
 * Class Guzzle_Autoload
 */
class Guzzle_Autoload
{
    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function load()
    {
        return ComposerAutoloaderInit396a5844e99ce4e41f188b3edd371501::getLoader();
    }
}

Guzzle_Autoload::load();
